name: Register Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to register or component to bump (without leading 'v' e.g. '1.0.1')"
        required: true
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}